# main/.github/workflows/dispatch-docs.yml
on:
  issue_comment:
    types: [created]

jobs:
  trigger-docs:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/docs') }}
    uses: centdix/windmilldocs/.github/workflows/create-docs.yml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
      pr_branch: ${{ github.event.pull_request.head.ref }}
      repo: ${{ github.event.repository.name }}
      comment_text: ${{ github.event.comment.body }}
    secrets:
      DOCS_TOKEN: ${{ secrets.DOCS_TOKEN }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
